name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Linux,   os: ubuntu-latest }
        #- { name: Windows, os: windows-2025 }
        #- { name: MacOS,   os: macos-latest }
    steps:
    - name: Set up Macos dependencies
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install \
          libtool \
          ninja \
          flac \
          fluidsynth \
          game-music-emu \
          libvorbis \
          libxmp \
          mpg123 \
          opusfile \
          wavpack \
          ${NULL+}
    - name: Set up Linux dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          cmake \
          libasound2-dev \
          libflac-dev \
          fluidsynth \
          libgme-dev \
          libmpg123-dev \
          libopusfile-dev \
          libvorbis-dev \
          libxmp-dev \
          libwavpack-dev \
          ninja-build \
          pkg-config \
          ${NULL+}
    - name: Get SDL_remixer sources
      uses: actions/checkout@v4
    - name: Set up SDL
      id: sdl
      uses: libsdl-org/setup-sdl@v1
      with:
        version: sdl3-head
    - name: Configure CMake
      run: cmake -B build ${{ matrix.platform.flags }}
    - name: Build
      run: cmake --build build/
